name: disaster-prediction
channels:
  - conda-forge
dependencies:
  - black
  - flake8
  - isort
  - pip
  - python=3.10
  - kaggle
  - pandas
  - scikit-learn
  - transformers
  - pytorch
  - torchvision
  - ipywidgets
  - torchinfo
  - evaluate
  - prettytable
  - plotly
  - typer
  - pip:
    - python-dotenv
    - mkdocs
    - -e .