name: disaster-prediction
channels:
  - conda-forge
dependencies:
  - black
  - evaluate
  - flake8
  - ipywidgets
  - isort
  - kaggle
  - pandas
  - pip
  - plotly
  - prettytable
  - python=3.10
  - pytorch
  - scikit-learn
  - torchinfo
  - torchvision
  - transformers
  - typer
  - ipykernel