name: disaster-prediction
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - black
  - evaluate
  - flake8
  - ipywidgets
  - isort
  - kaggle
  - pandas
  - pip
  - plotly
  - prettytable
  - python=3.10
  - pytorch
  - scikit-learn
  - torchinfo
  - torchvision
  - transformers
  - typer
  - ipykernel